# 워크 플로우 이름 : 우분투 서버에서 빌드와 배포를 위한 워크 플로우
name: "Build and Deploy to Ubuntu Server Run"

# main 브랜치에 push 가 발생하면 jobs가 실행되도록 이벤트 설정
on:
  push:
    branches:
      - main # main 브랜치에 push 가 발생하면

# 위에 설정된 push 이벤트를 실행할 job들의 순서를 정한다.
jobs:
  # 첫번째 단계 : 빌드
  build:
    runs-on: [self-hosted, fungle-server]

    steps:
      - name: Build Next.js Project
        run: echo "Build Next.js Project"
  # 두번째 단계: 테스트
  test:
    runs-on: [self-hosted, fungle-server]

    steps:
      - name: Test Next.js Project
        run: echo "Test Next.js Project"

  # 세번째 단계: 배포
  deploy:
    runs-on: [self-hosted, fungle-server]

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      NEXT_PUBLIC_BASE_URL: ${{  secrets.NEXT_PUBLIC_BASE_URL }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}

    
    steps:
      - name: Deploy Next.js Project
        run: /home/fungle/www/fungle/fungle-update.sh
